_target_: bayesrul.data.ncmapss.dataset.NCMAPSSDataModule
data_path: ${paths.data_dir}/ncmapss/
batch_size: 100 # train/val batch size
test_batch_size: 10000
all_dset: False
num_workers: 12
pin_memory: True
