# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  #- dataset: ncmapss
  - datamodule: ncmapss
  - model: hnn
  - callbacks: default
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  - hparams_search: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

task_name: train
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null
