_target_: optuna.create_study
direction: minimize
study_name: ncmapss
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 1234
  n_startup_trials: 10 # number of random sampling runs before optimization starts
pruner:
  _target_: optuna.pruners.PatientPruner
  wrapped_pruner:
    _target_: optuna.pruners.MedianPruner
  patience: 10
storage: ???
load_if_exists: True
